services:
  channel-archiver:
    user: "1000:1000"
    build: .
    env_file:
      - .env
    init: true
    command: ["telegram-archiver", "channels"]
    volumes:
      - /srv/nas/nasdata/saved-archiver:/app/downloads
      - ./data:/app/data
    restart: unless-stopped
