services:
  bot:
    user: "1000:1000"
    build: .
    env_file:
      - .env
    init: true
    volumes:
      - /srv/nas/nasdata/telegram-forward-archiver-bot/downloads:/app/downloads
      - ./data:/app/data
    restart: unless-stopped
  saved-archiver:
    user: "1000:1000"
    build: .
    env_file:
      - .env
    init: true
    command: ["tele-saved-archiver"]
    volumes:
      - /srv/nas/nasdata/telegram-forward-archiver-bot/downloads:/app/downloads
      - ./data:/app/data
    restart: unless-stopped
